# Generated by Django 5.0.2 on 2024-02-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(blank=True, choices=[('product manager', 'Product Manager'), ('supervisor', 'Supervisor'), ('operator', 'Operator'), ('customer', 'Customer')], max_length=100, null=True),
        ),
    ]
