# Generated by Django 5.0.2 on 2024-02-13 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(choices=[('men', 'Men'), ('women', 'Women')], on_delete=django.db.models.deletion.CASCADE, to='Products.category'),
        ),
    ]
