# Generated by Django 5.0.2 on 2024-02-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_category_is_active_comment_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('decimal', 'Decimal')], max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(choices=[('available', 'Available'), ('finished', 'Finished')], max_length=250),
        ),
    ]
